# Generated by Django 3.2.9 on 2021-11-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgalunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
